### ISSUE TITLE
Launching SKR with doas instead of sudo does not work.

### ISSUE THREAD

**Issue by Kommynct** [DavRack/skr#12]
opendoas is pretty commonly used on archlinux these days, if you have opendoas and opendoas-sudo (which symlinks sudo to opendoas) skr will not launch at all.

even trying to run skr with doas just fails.

**Comment by DavRack** [comment]
Will take a look later today, thanks!

**Comment by DavRack** [comment]
33107f3 fix this issue, thanks for the info

**Comment by Kommynct** [comment]
Launching with doas still does not work for me on the latest master, gives me "operation not permitted"
