### ISSUE TITLE
Unclear error messages

### ISSUE THREAD

**Issue by poldi1405** [DavRack/skr#14]
![20210217_08h44m57s_grim](https://user-images.githubusercontent.com/33086936/108172262-84f65780-70f4-11eb-976a-1377ffdcb195.png)

So according to `skr --init` I have to run it using sudo (`sudo -u name skr --init` does not work obviously) and `sudo skr --init` tells me that it must not be run as root but works otherwise.

**Comment by DavRack** [comment]
thanks for your feedback, i pls try again using the latest commit

**Comment by poldi1405** [comment]
Works now, thanks.

**Comment by poldi1405** [comment]
I now also get this glorious message:
![20210218_08h41m27s_grim](https://user-images.githubusercontent.com/33086936/108322021-d9fda080-71bc-11eb-8b2f-15357c692222.png)

**Comment by poldi1405** [comment]
Ignore the first PR. It's still early.

**Comment by DavRack** [comment]
so ... i have fixed the error, it's in master, i didn't saw your PR at that time, sorry.
