### ISSUE TITLE
skr v2, new config file, rewrite in Go ideas and suggestions wanted!

### ISSUE THREAD

**Issue by DavRack** [DavRack/skr#20]
Hi everyone!
Thanks to all of you for using skr, I know I've been very distant from the project (school and work can get in the way sometimes) but I have some ideas to improve skr, some of them I already decided but another ones I want some feedback. Some of the things I have already decided:
1. skr will be rewritten entirely in Go
2. skr will have some new features like many to one remaps, tap key etc

the things I'm not so sure about:
1. config file: I think we need to use a standard config file like JSON, YML or HCL. I love JSON for data exchange, but I don't think it would be a good fit for skr, I think yml is fine but it being indentation only makes it a bit flaky, I think the best option would be hcl, but I want to hear what you guys think.

I hope with skr v2 we can solve all current open issues. As always, if you have some suggestions, I'm happy to hear them
(any other things I would be adding to this issue)

**Comment by aaronamk** [comment]
I always use INI format if at all possible. It's dead simple which is what you want for command line utilities like this. There's also the format used for the sxhkd config which isn't standard, but is also simple.
