### ISSUE TITLE
Support multiple keyboards

### ISSUE THREAD

**Issue by gnufied** [DavRack/skr#5]
I was looking at the parser code and the way it has been written, it appears that it can't support multiple keyboards.

For example - I am using skr to bind capslock to control, but as far as I can tell, I can define only one keyboard. This makes it hard to use skr on a laptop which can have external USB keyboards.

**Comment by DavRack** [comment]
Hi @gnufied suport for multiple keyboards is defenetly something i would like, its actualy not too dificult to implement.

**Comment by DavRack** [comment]
@gnufied i have implemented the necessary changes in a new branch https://github.com/DavRack/skr/tree/multikeyboard pls test it.
Each keyboard needs a new config file, now you can use "skr --init" to generate a config file for each keyboard.
Tell me what you think.

**Comment by gnufied** [comment]
hmm, so if I understand this code correctly - it does ask for config filename but it does not actually do anything - https://github.com/DavRack/skr/blob/multikeyboard/skr#L38 ?

**Comment by DavRack** [comment]
yeah... something mess up there. I've corrected, pls check it
