### ISSUE TITLE
Automatic keyboard detection

### ISSUE THREAD

**Issue by gnufied** [DavRack/skr#7]
I think which keyboards to use with skr can be entirely automated and can be done at runtime. This is important for users like me who hotplug their laptops into docking stations and such.

It should be possible to use `/proc/bus/input/devices` and then output like:

```
  85   │ I: Bus=0003 Vendor=046d Product=408a Version=0111
  86   │ N: Name="Logitech MX Keys"
  87   │ P: Phys=usb-0000:04:00.4-2/input2:1
  88   │ S: Sysfs=/devices/pci0000:00/0000:00:08.1/0000:04:00.4/usb5/5-2/5-2:1.2/0003:046D:C52B.0003/0003:046D:408A.0004/input/input29
  89   │ U: Uniq=408a-86-3b-a4-97
  90   │ H: Handlers=sysrq kbd leds mouse0 event5 
  91   │ B: PROP=0
  92   │ B: EV=12001f
  93   │ B: KEY=3f000301ff 0 0 483ffff17aff32d bfd4444600000000 ffff0001 130ff38b17c007 ffff7bfad941dfff ffbeffdfffefffff fffffffffffffffe
  94   │ B: REL=1943
  95   │ B: ABS=100000000
  96   │ B: MSC=10
  97   │ B: LED=1f
```

to detect keyboards attached to the machine. In this case for example keyboard will be available on `/dev/input/event5` (See `Handlers` section)

**Comment by DavRack** [comment]
So... If i understand correctly that would enable a config file to work with multiple keyboards? After 18a7a24b562f6b3915cb9bfafe8e272ea8e49b38 hot plugging a previously defined keyboard is posible.

**Comment by gnufied** [comment]
Yeah hotplugging a previously defined keyboard is possible now, but the problem is - event<x> path is not stable and changes sometimes. I could use `/dev/input/by-id` obviously but for some reason for some devices these symbolic links don't get created (may be something to do with udev)...

**Comment by DavRack** [comment]
So... I think its a great idea, I'm working on it. 
Currently the keyboard path is defined like this
`KeyboardPath -> /path/to/keyboard`
KeyboardPath will remain an option and "keyboardName" will be added, something like this 
`KeyboardName -> keyboard name`

Some things i have in mind:

1. KeyboardPath probably will remain as the default option when executing skr --init
2. I don't know how multiple keyboards with the same name will behave with `/proc/bus/input/devices` 

If someone has multiple same model keyboards pls post the output of `cat /proc/bus/input/devices`

**Comment by gnufied** [comment]
hmm, so I think sometimes I don't know why but multiple entries are created for same keyboard in `/proc/bus/input/devices`. For example:

```
199     |   N: Name="Logitech MX Keys"
 200   │ P: Phys=usb-0000:04:00.3-1.1/input2:1
 201   │ S: Sysfs=/devices/pci0000:00/0000:00:08.1/0000:04:00.3/usb3/3-1/3-1.1/3-1.1:1.2/0003:046D:C52B.000A/0003:046D:408A.000B/input/input47
 202   │ U: Uniq=408a-86-3b-a4-97
 203   │ H: Handlers=sysrq kbd leds mouse2 event21 
 204   │ B: PROP=0
 205   │ B: EV=12001f
 206   │ B: KEY=3f000301ff 0 0 483ffff17aff32d bfd4444600000000 ffff0001 130ff38b17c007 ffff7bfad941dfff ffbeffdfffefffff fffffffffffffffe
 207   │ B: REL=1943
 208   │ B: ABS=100000000
 209   │ B: MSC=10
 210   │ B: LED=1f
 211   │ 
 212   │ I: Bus=0003 Vendor=046d Product=406d Version=0111
 213   │ N: Name="Logitech M705"
 214   │ P: Phys=usb-0000:04:00.3-1.1/input2:2
 215   │ S: Sysfs=/devices/pci0000:00/0000:00:08.1/0000:04:00.3/usb3/3-1/3-1.1/3-1.1:1.2/0003:046D:C52B.000A/0003:046D:406D.000C/input/input48
 216   │ U: Uniq=406d-ab-24-60-fa
 217   │ H: Handlers=mouse3 event22 
 218   │ B: PROP=0
 219   │ B: EV=17
 220   │ B: KEY=ffff0000 0 0 0 0
 221   │ B: REL=1943
 222   │ B: MSC=10
 223   │ 
 224   │ I: Bus=0003 Vendor=046d Product=4057 Version=0111
 225   │ N: Name="Logitech B330/M330/M331"
 226   │ P: Phys=usb-0000:04:00.3-1.1/input2:3
 227   │ S: Sysfs=/devices/pci0000:00/0000:00:08.1/0000:04:00.3/usb3/3-1/3-1.1/3-1.1:1.2/0003:046D:C52B.000A/0003:046D:4057.000D/input/input49
 228   │ U: Uniq=4057-37-8e-af-52
 229   │ H: Handlers=mouse4 event23 
 230   │ B: PROP=0
 231   │ B: EV=17
 232   │ B: KEY=ffff0000 0 0 0 0
 233   │ B: REL=1943
 234   │ B: MSC=10
 235   │ 
 236   │ I: Bus=0011 Vendor=0001 Product=0001 Version=0000
 237   │ N: Name="AT Translated Set 2 keyboard"
 238   │ P: Phys=
 239   │ S: Sysfs=/devices/virtual/input/input51
 240   │ U: Uniq=
 241   │ H: Handlers=sysrq kbd leds event19 
 242   │ B: PROP=0
 243   │ B: EV=120013
 244   │ B: KEY=402000000 3803078f800d001 feffffdfffefffff fffffffffffffffe
 245   │ B: MSC=10
 246   │ B: LED=7
 247   │ 
 248   │ I: Bus=0003 Vendor=046d Product=408a Version=0000
 249   │ N: Name="Logitech MX Keys"
 250   │ P: Phys=
 251   │ S: Sysfs=/devices/virtual/input/input52
 252   │ U: Uniq=
 253   │ H: Handlers=sysrq kbd leds mouse5 event20 
 254   │ B: PROP=0
 255   │ B: EV=12001f
 256   │ B: KEY=3f000301ff 0 0 483ffff17aff32d bfd4444600000000 ffff0001 130ff38b17c007 ffff7bfad941dfff ffbeffdfffefffff fffffffffffffffe
 257   │ B: REL=1943
 258   │ B: ABS=100000000
 259   │ B: MSC=10
 260   │ B: LED=1f
```
We can see I got two entries for `MX Keys` - one appears to be for real device and other one appears to be for some kind of virtual input device. Using event id from real input device works but not from virtual one.

We got to be careful about this at least.

**Comment by DavRack** [comment]
I was referring to plugging multiple keyboards, say 2 MX keys and see how /proc/bus/input/devices handles that. For keyboards with different name i think it's done.

**Comment by DavRack** [comment]
@gnufied pls check #8
